### ISSUE TITLE
关于CAN帧协议

### ISSUE THREAD

**Issue by CmST0us** [Tony607/Cybergear#1]
https://github.com/Tony607/Cybergear/blob/5da4240b276ac4c7c7bddbe00afa9ebe58292ca9/01_web_simple_control/main.py#L26C8-L26C8

`send_command('41 54 90 07 eb fc 08 05 70 00 00 07 01 95 54 0d 0a')`

按照小米提供的文档，
`41 54` 是USB CAN模块的帧头 `0d 0a` 是USB CAN模块的帧尾

`90 07 eb fc` 前4字节组成 CAN_ID ,这里是写入单个参数

`08` 推测是USB CAN模块，用于区分 CAN_ID 和 CAN_DATA 的分隔符

`05 70 00 00 07 01 95 54` 后8字节作为数据字节， 其中

`05 70` 是 参数 index ,对应电机运行模式，

 `07 01 95 54` 是具体的参数，但是根据文档，电机运行模式的参数值只有 0 1 2 3 这几个选项，不太明白这里为什么设置的是这个值

**Comment by Tony607** [comment]
UART转CAN模块中的数据帧比较复杂，不太好理解，并不是按字节和CAN协议对其的。
可以参考我最近做的通过原生CAN协议的PCAN适配器和电机通讯的视频：https://www.bilibili.com/video/BV1Qu411P73S

**Comment by CmST0us** [comment]
> UART转CAN模块中的数据帧比较复杂，不太好理解，并不是按字节和CAN协议对其的。 可以参考我最近做的通过原生CAN协议的PCAN适配器和电机通讯的视频：https://www.bilibili.com/video/BV1Qu411P73S

好的感谢，我最近也在写C版本的CyberGear电机库，参考一下你的协议～
